# Generated by Django 4.0.1 on 2022-01-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=30)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('Images', models.ImageField(upload_to='C:\\Users\\user\\Desktop\\New folder\\Books_img')),
                ('Author_name', models.CharField(max_length=30)),
                ('Discription', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
