# Generated by Django 3.2.8 on 2022-01-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Author_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='Book_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='Discription',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
